before_install:
- openssl aes-256-cbc -K $encrypted_9cf28b65941a_key -iv $encrypted_9cf28b65941a_iv
  -in fh-deploy.enc -out fh-deploy -d

language: node_js
node_js:
  - "7"
env: 
  global:
  - NODE_ENV=production
addons:
  ssh_known_hosts: floridahackers.com
before_install:
- bash _scripts/install.sh
script:
- bash _scripts/build.sh
after_success:
- bash _scripts/deploy.sh